<?php
/**
 * @copyright Copyright (c) Hustle Hero
 */


namespace common\base\db\pgsql;

/**
 * Class QueryBuilder
 * @package common\base\db\pgsql
 */
class QueryBuilder extends \yii\db\pgsql\QueryBuilder
{
    /**
     * @var array mapping from abstract column types (keys) to physical column types (values).
     */
    public $typeMap = [
        Schema::TYPE_BIG_IDENTITY_ALWAYS => 'BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY',
        Schema::TYPE_BIG_IDENTITY_DEFAULT => 'BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY',
        Schema::TYPE_UUIDPK => 'uuid NOT NULL PRIMARY KEY DEFAULT gen_random_uuid()',
        Schema::TYPE_UUID => 'uuid',
        Schema::TYPE_NANOID_PK => 'varchar(36) NOT NULL PRIMARY KEY DEFAULT nanoid()',
        Schema::TYPE_NANOID => 'varchar(36)',
        Schema::TYPE_TSVECTOR => 'tsvector',
        Schema::TYPE_TIMESTAMP_TIMEZONE => 'timestamptz',
        Schema::TYPE_TEXT_ARRAY => 'text[]',
        Schema::TYPE_UUID_ARRAY => 'uuid[]',

        //-- below are copy from parents
        Schema::TYPE_PK => 'serial NOT NULL PRIMARY KEY',
        Schema::TYPE_UPK => 'serial NOT NULL PRIMARY KEY',
        Schema::TYPE_BIGPK => 'bigserial NOT NULL PRIMARY KEY',
        Schema::TYPE_UBIGPK => 'bigserial NOT NULL PRIMARY KEY',
        Schema::TYPE_CHAR => 'char(1)',
        Schema::TYPE_STRING => 'varchar(255)',
        Schema::TYPE_TEXT => 'text',
        Schema::TYPE_TINYINT => 'smallint',
        Schema::TYPE_SMALLINT => 'smallint',
        Schema::TYPE_INTEGER => 'integer',
        Schema::TYPE_BIGINT => 'bigint',
        Schema::TYPE_FLOAT => 'double precision',
        Schema::TYPE_DOUBLE => 'double precision',
        Schema::TYPE_DECIMAL => 'numeric(10,0)',
        Schema::TYPE_DATETIME => 'timestamp(0)',
        Schema::TYPE_TIMESTAMP => 'timestamp(0)',
        Schema::TYPE_TIME => 'time(0)',
        Schema::TYPE_DATE => 'date',
        Schema::TYPE_BINARY => 'bytea',
        Schema::TYPE_BOOLEAN => 'boolean',
        Schema::TYPE_MONEY => 'numeric(19,4)',
        Schema::TYPE_JSON => 'jsonb',
    ];
}