<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'avatar.content' => 'Content',
    'identity_bind.idToken' => 'idToken',
    'identity_bind.type' => 'Type',
    'image.content' => 'Content',
    'image.mime' => 'MIME',
    'password.change.confirm_password' => 'Confirm Password',
    'password.change.current_password' => 'Current Password',
    'password.change.error.incorrect_current_password' => 'Current Password Incorrect',
    'password.change.new_password' => 'New Password',
    'password.confirm_password' => 'Confirm Password',
    'password.new_password' => 'New Password',
    'sign_in.idToken' => 'ID Token',
    'sign_in.password' => 'Password',
    'sign_in.referrerCode' => 'Reference Code',
    'sign_in.username' => 'Username',
];
