<?php
/**
 * @copyright Copyright (c) Hustle Hero
 */

/**
 * Configuration file for 'yii message/extract' command.
 *
 * This file is automatically generated by 'yii message/config' command.
 * It contains parameters for source code messages extraction.
 * You may modify this file to suit your needs.
 *
 * You can use 'yii message/config-template' command to create
 * template configuration file with detaild description for each parameter.
 */
return [
    'color' => null,
    'interactive' => true,
    'sourcePath' => '@common/..',
    'messagePath' => '@common/messages',
    'languages' => \common\base\enum\LanguageCode::getSupported(),
    'translator' => 'Yii::t',
    'sort' => true,
    'overwrite' => true,
    'removeUnused' => true,
    'markUnused' => false,
    'except' => [
        '.svn',
        '.git',
        '.gitignore',
        '.gitkeep',
        '.hgignore',
        '.hgkeep',
        '/common/mail/zurb',
        '/common/rbac',
        '/common/messages',
        '/common/fixtures',
        '/common/tests',
        '/frontend/tests',
        '/frontend/assets/website',
        '/frontend/web/assets',
        '/backend/tests',
        '/backend/assets/dist',
        '/backend/assets/adminlte',
        '/backend/assets/vue-app',
        '/backend/assets/vuejs',
        '/backend/web/assets',
        '/backend/web/libs',
        '/api/tests',
        '/_apidoc',
        '/_develop',
        '/test',
        '/uploads',
        '/vendor',
        '/messages',
        '/console',
        '/environments',
        '/BaseYii.php',
    ],
    'only' => [
        '*.php',
    ],
    'format' => 'php',
    'db' => 'db',
    'sourceMessageTable' => '{{%translation_source_message}}',
    'messageTable' => '{{%translation_message}}',
    'catalog' => 'messages',
    'ignoreCategories' => [],
];
