<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'agent.listing_create_success' => 'Property created !',
    'agent.listing_publish_success' => 'Property published !',
    'agent.listing_update_success' => 'Property updated !',
    'agent.register_success' => 'Register Success !',
    'agent.subscription_update_success' => 'Subscription updated !',
    'agent.verify_success' => 'Account verified !',
    'auth.login_success_message' => 'Login Success !',
    'common.failed_to_complete_request_for_unknown_reason' => 'Failed to complete request for unknown reason !!',
    'image.create.success' => 'Image uploaded !',
    'image.delete.success' => 'Image deleted !',
    'image.primary.success' => 'Primary image update !',
    'image.sort.success' => 'Image Sorted !',
    'me.avatar_success_message' => 'Avatar updated !',
    'me.bind_success_message' => 'Successfully linked !',
    'me.profile_update_success_message' => 'Profile updated !',
    'model.not_found' => 'Record Not Found !!',
];
