<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'account.agent.list' => 'Agent Accounts',
    'account.developer.list' => 'Developer Accounts',
    'account.user-project.list' => 'User Project',
    'content-management.faq.list' => 'FAQ Management',
    'content-management.home-popup.list' => 'Home Popup Setup',
    'content-management.news.list' => 'News Management',
    'content-management.page.list' => 'Page Management',
    'general.agency.list' => 'Agency Management',
    'general.developer.list' => 'Developer Management',
    'general.project.list' => 'System Projects',
    'general.user.list' => 'User Management',
    'lead.agent.list' => 'Agent Leads',
    'site.login' => 'Login',
    'system.audit.trail' => 'Audit Trail',
    'system.cache.flush' => 'Flush Cache',
    'system.setting.index' => 'Settings',
    'ugc.account.list' => 'Accounts List',
    'ugc.agency.list' => 'Agency List',
    'ugc.developer.list' => 'Developer List',
    'ugc.project.list' => 'Developer Projects',
    'ugc.property.list' => 'Agency Properties',
    'website.faq.list' => 'FAQ Management',
    'website.home_banner.list' => 'Home Banner Management',
    'website.page.list' => 'Page Management',
];
